version: '3.9'
services:
  mysql-contenedor:
    image: mysql:5.7
    container_name: mysql-contenedor
    restart: always
    environment:
      MYSQL_DATABASE: 'spotify-dev-mysql'
      MYSQL_USER: 'usr-spotify-mysql'
      MYSQL_PASSWORD: 'pwd-spotify-mysql'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: [ "CMD", "usr-spotify-mysql", "ping", "-ppwd-spotify-mysql", "--silent" ]
      interval: 5s
      timeout: 3s
      retries: 10
  mongocontenedor:
    image: mongo
    container_name: mongocontenedor
    restart: always
    environment:
      MONGO_INITDB_DATABASE: 'spotifydevmongo'
      MONGO_INITDB_ROOT_USERNAME: 'usrspotifymongo'
      MONGO_INITDB_ROOT_PASSWORD: 'pwdspotifymongo'
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  zipkin-contenedor:
    image: openzipkin/zipkin-slim
    container_name: zipkin-contenedor
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    expose:
      - 9411
    depends_on:
      - storage-contenedor
  storage-contenedor:
    image: busybox:1.31.0
    container_name: storage-contenedor

  rabbitmq-contenedor:
    image: rabbitmq:3-management
    container_name: rabbitmq-contenedor
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 15672
      - 5672