server:
  port: 8888
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TomasArrinda/esp-back-i-parcial-tomas-arrinda
          search-paths: esp-back-i-parcial-tomas-arrinda/ConfigData/
          default-label: develop
          force-pull: true