server:
  port: 8083
spring:
  application:
    name: api-serie
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017
  cloud:
    config:
      server:
        git:
          url: https://github.com/TomasArrinda/esp-back-i-parcial-tomas-arrinda
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
resilience4j.retry:
  instances:
    retryMusic:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
resilience4j.circuitbreaker:
  instances:
    clientMusic:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10