server:
  port: 8081
spring:
  application:
    name: api-catalog
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    config:
      server:
        git:
          url: https://github.com/TomasArrinda/esp-back-i-parcial-tomas-arrinda
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka