server:
  port: 8082
spring:
  application:
    name: api-movie
  data:
    mongodb:
      mongodb:
        username: Tomas
        password: TestTest
        database: test
        port: 27017
        host: cluster0.hmkrq1v.mongodb.net
  cloud:
    config:
      server:
        git:
          url: https://github.com/TomasArrinda/esp-back-i-parcial-tomas-arrinda
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  sleuth:
    sampler:
      probability: 1.0
    rabbitmq:
      addresses: localhost:5672
      virtual-host: app_vhost
      username: guest
      password: guest
    zipkin:
      baseUrl: http://localhost:9411/
      sender:
        type: rabbit
      enabled: true
queue:
  serie:
    name: movieQueue
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka