server:
  port: 8083
spring:
  application:
    name: api-serie
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: mongodb+srv://Tomas:TestTest@cluster0.hmkrq1v.mongodb.net/test
#    username: root
#    password: root
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        format-sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
#      host: localhost
  data:
    mongodb:
      username: Tomas
      password: TestTest
      uri: mongodb+srv://Tomas:TestTest@cluster0.hmkrq1v.mongodb.net/test
      database: db
  cloud:
    config:
      server:
        git:
          url: https://github.com/TomasArrinda/esp-back-i-parcial-tomas-arrinda
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  sleuth:
    sampler:
      probability: 1.0
    rabbitmq:
      addresses: localhost:5672
      virtual-host: app_vhost
      username: guest
      password: guest
    zipkin:
      baseUrl: http://localhost:9411/
      sender:
        type: rabbit
      enabled: true
queue:
  serie:
    name: serieQueue
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
resilience4j.retry:
  instances:
    retryMusic:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
resilience4j.circuitbreaker:
  instances:
    clientMusic:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10