server:
  port: 8083
spring:
  application:
    name: api-serie
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    config:
      server:
        git:
          url: https://github.com/TomasArrinda/esp-back-i-parcial-tomas-arrinda
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka